name=solr-sink
connector.class=com.una.kafka.connect.solr.SolrSinkConnector
tasks.max=1
topics=aggregated-user-data

solr.url=http://solr:8983/solr
solr.collection=aggregated-user-data

key.ignore=false
schema.ignore=true
behavior.on.null.values=delete

batch.size=2000
linger.ms=50
max.in.flight.requests=8
max.buffered.records=20000
max.retries=5
retry.backoff.ms=200

write.method=INDEX
id.strategy=KAFKA_KEY

key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false

transforms=InsertKey,extractKey,WKBToLatLon
transforms.InsertKey.type=org.apache.kafka.connect.transforms.ValueToKey
transforms.InsertKey.fields=id
transforms.extractKey.type=org.apache.kafka.connect.transforms.ExtractField$Key
transforms.extractKey.field=id
transforms.WKBToLatLon.type=com.una.kafka.connect.solr.transforms.WKBToLatLon
transforms.WKBToLatLon.field=location

consumer.auto.offset.reset=earliest
