package com.una.kafka.connect.solr;

import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Exhaustive branch coverage for SolrSinkConfig getters whose conditionals are
 * not exercised by the functional tests (password null-checks, proxy/kerberos
 * enabled flags, autogenerated-ids override, etc.).
 */
class SolrSinkConfigCoverageTest {

    private SolrSinkConfig with(Map<String, String> extras) {
        Map<String, String> p = new HashMap<>();
        p.put(SolrSinkConfig.SOLR_URL_CONFIG, "http://x");
        p.putAll(extras);
        return new SolrSinkConfig(p);
    }

    @Test
    void passwordDefaultsToEmptyWhenUnset() {
        SolrSinkConfig c = with(new HashMap<>());
        assertThat(c.password()).isEmpty();
        assertThat(c.proxyPassword()).isEmpty();
        assertThat(c.sslKeystorePassword()).isEmpty();
        assertThat(c.sslKeyPassword()).isEmpty();
        assertThat(c.sslTruststorePassword()).isEmpty();
    }

    @Test
    void passwordReturnsValueWhenSet() {
        Map<String, String> p = new HashMap<>();
        p.put(SolrSinkConfig.CONNECTION_PASSWORD_CONFIG, "secret");
        p.put(SolrSinkConfig.PROXY_PASSWORD_CONFIG, "pp");
        p.put(SolrSinkConfig.SSL_KEYSTORE_PASSWORD_CONFIG, "ksp");
        p.put(SolrSinkConfig.SSL_KEY_PASSWORD_CONFIG, "kp");
        p.put(SolrSinkConfig.SSL_TRUSTSTORE_PASSWORD_CONFIG, "tsp");
        SolrSinkConfig c = with(p);
        assertThat(c.password()).isEqualTo("secret");
        assertThat(c.proxyPassword()).isEqualTo("pp");
        assertThat(c.sslKeystorePassword()).isEqualTo("ksp");
        assertThat(c.sslKeyPassword()).isEqualTo("kp");
        assertThat(c.sslTruststorePassword()).isEqualTo("tsp");
    }

    @Test
    void proxyEnabledRequiresHostAndPositivePort() {
        // No host -> off
        assertThat(with(new HashMap<>()).proxyEnabled()).isFalse();

        // Host but port=0 -> off
        Map<String, String> p1 = new HashMap<>();
        p1.put(SolrSinkConfig.PROXY_HOST_CONFIG, "h");
        assertThat(with(p1).proxyEnabled()).isFalse();

        // Host + port -> on
        Map<String, String> p2 = new HashMap<>();
        p2.put(SolrSinkConfig.PROXY_HOST_CONFIG, "h");
        p2.put(SolrSinkConfig.PROXY_PORT_CONFIG, "3128");
        assertThat(with(p2).proxyEnabled()).isTrue();

        // Empty host -> off
        Map<String, String> p3 = new HashMap<>();
        p3.put(SolrSinkConfig.PROXY_HOST_CONFIG, "");
        p3.put(SolrSinkConfig.PROXY_PORT_CONFIG, "3128");
        assertThat(with(p3).proxyEnabled()).isFalse();
    }

    @Test
    void kerberosEnabledRequiresBothPrincipalAndKeytab() {
        // None
        assertThat(with(new HashMap<>()).kerberosEnabled()).isFalse();

        // Principal only
        Map<String, String> p1 = new HashMap<>();
        p1.put(SolrSinkConfig.KERBEROS_PRINCIPAL_CONFIG, "user@REALM");
        assertThat(with(p1).kerberosEnabled()).isFalse();

        // Keytab only
        Map<String, String> p2 = new HashMap<>();
        p2.put(SolrSinkConfig.KERBEROS_KEYTAB_PATH_CONFIG, "/x.keytab");
        assertThat(with(p2).kerberosEnabled()).isFalse();

        // Both -> on
        Map<String, String> p3 = new HashMap<>();
        p3.put(SolrSinkConfig.KERBEROS_PRINCIPAL_CONFIG, "user@REALM");
        p3.put(SolrSinkConfig.KERBEROS_KEYTAB_PATH_CONFIG, "/x.keytab");
        assertThat(with(p3).kerberosEnabled()).isTrue();
    }

    @Test
    void sslEnabledFromSecurityProtocol() {
        assertThat(with(new HashMap<>()).sslEnabled()).isFalse(); // default PLAINTEXT
        Map<String, String> p = new HashMap<>();
        p.put(SolrSinkConfig.SECURITY_PROTOCOL_CONFIG, "SSL");
        assertThat(with(p).sslEnabled()).isTrue();
    }

    @Test
    void idStrategyHonorsAutogenerated() {
        Map<String, String> p = new HashMap<>();
        p.put(SolrSinkConfig.USE_AUTOGENERATED_IDS_CONFIG, "true");
        p.put(SolrSinkConfig.ID_STRATEGY_CONFIG, "RECORD_FIELD");
        // useAutogeneratedIds=true overrides the explicit strategy.
        assertThat(with(p).idStrategy()).isEqualTo(SolrSinkConfig.IdStrategy.UUID);
    }

    @Test
    void idStrategyParsesExplicitWhenAutogeneratedFalse() {
        Map<String, String> p = new HashMap<>();
        p.put(SolrSinkConfig.ID_STRATEGY_CONFIG, "TOPIC_PARTITION_OFFSET");
        assertThat(with(p).idStrategy()).isEqualTo(SolrSinkConfig.IdStrategy.TOPIC_PARTITION_OFFSET);
    }

    @Test
    void externalVersioningEnabledWhenHeaderSet() {
        assertThat(with(new HashMap<>()).externalVersioningEnabled()).isFalse();
        Map<String, String> p = new HashMap<>();
        p.put(SolrSinkConfig.EXTERNAL_VERSION_HEADER_CONFIG, "__kafka_offset");
        assertThat(with(p).externalVersioningEnabled()).isTrue();
    }

    @Test
    void behaviorOnMalformedDropInvalidAlias() {
        Map<String, String> p = new HashMap<>();
        p.put(SolrSinkConfig.DROP_INVALID_MESSAGE_CONFIG, "true");
        // drop.invalid.message=true forces IGNORE regardless of explicit setting.
        p.put(SolrSinkConfig.BEHAVIOR_ON_MALFORMED_DOCS_CONFIG, "fail");
        assertThat(with(p).behaviorOnMalformed()).isEqualTo(SolrSinkConfig.BehaviorOnMalformed.IGNORE);
    }

    @Test
    void isCloudReflectsZkHost() {
        assertThat(with(new HashMap<>()).isCloud()).isFalse();
        Map<String, String> p = new HashMap<>();
        p.put(SolrSinkConfig.SOLR_ZK_HOST_CONFIG, "zk:2181/solr");
        assertThat(with(p).isCloud()).isTrue();
    }

    @Test
    void miscellaneousGettersDoNotThrow() {
        SolrSinkConfig c = with(new HashMap<>());
        // Touch every defaulted getter to lock in the no-throw contract for downstream callers.
        c.connectionTimeoutMs();
        c.readTimeoutMs();
        c.maxConnectionIdleMs();
        c.connectionCompression();
        c.compressionAlgorithm();
        c.compressRequests();
        c.proxyHost();
        c.proxyPort();
        c.proxyUsername();
        c.securityProtocol();
        c.sslKeystoreLocation();
        c.sslKeystoreType();
        c.sslTruststoreLocation();
        c.sslTruststoreType();
        c.sslProtocol();
        c.sslEnabledProtocols();
        c.sslCipherSuites();
        c.sslEndpointIdentificationAlgorithm();
        c.kerberosPrincipal();
        c.kerberosKeytabPath();
        c.kerberosRenewWindowFactor();
        c.keyIgnore();
        c.schemaIgnore();
        c.compactMapEntries();
        c.dropInvalidMessage();
        c.behaviorOnNullValues();
        c.batchSize();
        c.bulkSizeBytes();
        c.lingerMs();
        c.flushTimeoutMs();
        c.flushSynchronously();
        c.maxInFlight();
        c.maxBufferedRecords();
        c.maxRetries();
        c.retryBackoffMs();
        c.idField();
        c.useAutogeneratedIds();
        c.externalVersionHeader();
        c.collectionNamingStrategy();
        c.schemaAutoCreate();
        c.autoCreateShards();
        c.autoCreateReplicationFactor();
        c.autoCreateConfigset();
        c.schemaAutoEvolve();
        c.externalResourceUsage();
        c.commitWithinMs();
        c.dryRun();
        c.mappingVersion();
        c.partitionFanoutEnabled();
        c.streamingEnabled();
        c.streamingQueueSize();
        c.streamingThreads();
        c.topicKeyIgnoreSet();
        c.topicSchemaIgnoreSet();
        c.writeMethod();
    }
}
