package com.una.kafka.connect.solr;

import org.apache.kafka.common.config.Config;
import org.apache.kafka.common.config.ConfigValue;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * {@link Validator} through the connector's real validate() with key material that exists on
 * disk (generated by keytool), a TOPIC_REGEX strategy with no collection at all, and a caller that
 * validates against a Config holding none of the connector's keys.
 */
class ValidatorRealFilesTest {

    private static TestKeystores stores;

    @BeforeAll
    static void keys() throws Exception {
        stores = TestKeystores.generate();
    }

    private static Map<String, ConfigValue> byName(Config c) {
        Map<String, ConfigValue> m = new HashMap<>();
        for (ConfigValue v : c.configValues()) m.put(v.name(), v);
        return m;
    }

    @Test
    void sslFilesThatExistPassValidation() {
        Map<String, String> p = new HashMap<>();
        p.put(SolrSinkConfig.SOLR_URL_CONFIG, "https://solr:8983/solr");
        p.put(SolrSinkConfig.SECURITY_PROTOCOL_CONFIG, "SSL");
        p.put(SolrSinkConfig.SSL_KEYSTORE_LOCATION_CONFIG, stores.keystore.toString());
        p.put(SolrSinkConfig.SSL_TRUSTSTORE_LOCATION_CONFIG, stores.truststore.toString());
        Map<String, ConfigValue> v = byName(new SolrSinkConnector().validate(p));
        assertThat(v.get(SolrSinkConfig.SSL_KEYSTORE_LOCATION_CONFIG).errorMessages()).isEmpty();
        assertThat(v.get(SolrSinkConfig.SSL_TRUSTSTORE_LOCATION_CONFIG).errorMessages()).isEmpty();
    }

    @Test
    void topicRegexWithoutAnyCollectionIsRejected() {
        Map<String, String> p = new HashMap<>();
        p.put(SolrSinkConfig.SOLR_URL_CONFIG, "http://solr:8983/solr");
        p.put(SolrSinkConfig.COLLECTION_NAMING_STRATEGY_CONFIG, "TOPIC_REGEX");
        Map<String, ConfigValue> v = byName(new SolrSinkConnector().validate(p));
        assertThat(v.get(SolrSinkConfig.SOLR_COLLECTION_CONFIG).errorMessages())
                .anySatisfy(m -> assertThat(m).contains("pattern=>replacement"));
    }

    @Test
    void errorsForKeysMissingFromTheBaseConfigAreDroppedNotThrown() {
        Config empty = new Config(Collections.emptyList());
        Map<String, String> p = new HashMap<>(); // no url, no zk -> would report on both keys
        assertThat(Validator.validate(empty, p).configValues()).isEmpty();
    }
}
